language: haxe

sudo: false

addons:
  apt:
    packages:
      - php5-cli
      - mono-devel
      - mono-mcs
      - python3
      - gcc-multilib
      - g++-multilib

matrix:
  include:
    - haxe: "3.1.3"
    - haxe: "3.2.1"
    - haxe: "development"
      install:
        # install and rebuild hxcpp
        - haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
        - cd $(haxelib path hxcpp | head -1)tools/hxcpp && haxe compile.hxml
        - cd $(haxelib path hxcpp | head -1)project && neko build.n
        - cd $TRAVIS_BUILD_DIR
        # install hxjava and hxcs
        - haxelib git hxjava https://github.com/HaxeFoundation/hxjava.git
        - haxelib git hxcs https://github.com/HaxeFoundation/hxcs.git
        - haxelib list
  allow_failures:
    - haxe: "development"

install:
  - yes | haxelib install hxcpp
  - yes | haxelib install hxjava
  - yes | haxelib install hxcs
  - haxelib list

script:
  - haxe -main Test --interp
  - haxe -main Test -cpp bin             && ./bin/Test
  - haxe -main Test -neko bin/Test.n     && neko bin/Test.n
  - haxe -main Test -php bin             && php bin/index.php
  - haxe -main Test -js bin/Test.js      && node bin/Test.js
  - haxe -main Test -java bin            && java -jar bin/Test.jar
  # There is a bug in the python target of haxe 3.2.1
  - if [ "${TRAVIS_HAXE_VERSION}" = "development" ]; then
      haxe -main Test -python bin/Test.py  && python3 bin/Test.py;
    fi
