language: php

# Install Haxe
before_script:
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - sudo apt-get install gcc-multilib g++-multilib -y  # for hxcpp
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxcpp
  - haxelib install utest
  - mkdir bin                                          # compilation output folder

script:
  - haxe -main Test -cpp bin           && ./bin/Test
  - haxe -main Test -neko bin/Test.n   && neko bin/Test.n
  - haxe -main Test -php bin           && php bin/index.php