language: php

# Install Haxe
before_script:
  - sudo apt-get install python-software-properties -y #for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
#  - sudo apt-get install ia32-libs-multiarch gcc-multilib g++-multilib #for hxcpp
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
#  - haxelib install hxcpp || true

script:
  - mkdir bin
  - haxe test.hxml