language: node_js

before_script:
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install php5 -y
  - sudo apt-get install haxe -y
  - sudo apt-get install gcc-multilib g++-multilib -y  # for hxcpp
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxcpp
  - haxelib install phantomjs
  - mkdir bin                                          # compilation output folder

script:
  - haxe -main Test -debug --interp
  - haxe -main Test -debug -cpp bin                       && ./bin/Test-debug
  - haxe -main Test -debug -neko bin/Test.n               && neko bin/Test.n
  - haxe -main Test -debug -php bin                       && php bin/index.php
  - haxe -main Test -debug -js bin/Test.js -lib phantomjs && phantomjs bin/Test.js